// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9ivZ79ar7JCdA6GqypkUPhhhbaZHrJuY',
    appId: '1:231823340883:web:00e0637e7912b330b1dda6',
    messagingSenderId: '231823340883',
    projectId: 'book-store-app-77e39',
    authDomain: 'book-store-app-77e39.firebaseapp.com',
    storageBucket: 'book-store-app-77e39.firebasestorage.app',
    measurementId: 'G-K32WQQY2QX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjiZUr7KHross0xE-_O-tD1DS1tc4Lsd8',
    appId: '1:231823340883:android:94d53255e63943d5b1dda6',
    messagingSenderId: '231823340883',
    projectId: 'book-store-app-77e39',
    storageBucket: 'book-store-app-77e39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK8cCEeOQX9I5k3U5nSPGTgTylQZUU4mc',
    appId: '1:231823340883:ios:7ff1978ad2d5a756b1dda6',
    messagingSenderId: '231823340883',
    projectId: 'book-store-app-77e39',
    storageBucket: 'book-store-app-77e39.firebasestorage.app',
    iosBundleId: 'com.example.bookStoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK8cCEeOQX9I5k3U5nSPGTgTylQZUU4mc',
    appId: '1:231823340883:ios:7ff1978ad2d5a756b1dda6',
    messagingSenderId: '231823340883',
    projectId: 'book-store-app-77e39',
    storageBucket: 'book-store-app-77e39.firebasestorage.app',
    iosBundleId: 'com.example.bookStoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9ivZ79ar7JCdA6GqypkUPhhhbaZHrJuY',
    appId: '1:231823340883:web:9eb9bbf179b8a7b3b1dda6',
    messagingSenderId: '231823340883',
    projectId: 'book-store-app-77e39',
    authDomain: 'book-store-app-77e39.firebaseapp.com',
    storageBucket: 'book-store-app-77e39.firebasestorage.app',
    measurementId: 'G-1FMY06KMNV',
  );
}
